### ISSUE TITLE
Path statico nel file bootstrap-lombardia.min.js

### ISSUE THREAD

**Issue by datrix88** [RegioneLombardia/bootstrap-lombardia#5]
## Comportamento attuale
In console vengono mostrati diversi errori 404 nel percorso **/bootstrap-italia/dist/fonts** che è definito staticamente nel file  **bootstrap-lombardia.min.js** presente in repository

## Possibili soluzioni
Per risolvere il problema è necessario rimuovere il path statico nella variabile var styleNode:

`var styleNode=document.createElement("style"),__PUBLIC_PATH__=window.__PUBLIC_PATH__?window.__PUBLIC_PATH__:"/bootstrap-italia/dist/fonts"`

come di seguito:

`var styleNode=document.createElement("style"),__PUBLIC_PATH__=window.__PUBLIC_PATH__?window.__PUBLIC_PATH__:"fonts"`

**Comment by EnzoFerri** [comment]
Grazie datrix88
